// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIq3n6fjiAOTR8FSFS-KAAK_D77LDudj8',
    appId: '1:883581912483:web:da30bfb3f4892c07374616',
    messagingSenderId: '883581912483',
    projectId: 'kombinb2',
    authDomain: 'kombinb2.firebaseapp.com',
    storageBucket: 'kombinb2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCetYCR4dBKL5UKadllySaZv4orCxEMgPw',
    appId: '1:883581912483:android:389b99aad6de2838374616',
    messagingSenderId: '883581912483',
    projectId: 'kombinb2',
    storageBucket: 'kombinb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSRztQttC9g3ah2keh2RYGG9r0GrHtydU',
    appId: '1:883581912483:ios:2bca5756134bcc0d374616',
    messagingSenderId: '883581912483',
    projectId: 'kombinb2',
    storageBucket: 'kombinb2.appspot.com',
    iosClientId: '883581912483-9st0vo4ekf8b2kug1i9ro0mfot13h2tc.apps.googleusercontent.com',
    iosBundleId: 'com.example.kB2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSRztQttC9g3ah2keh2RYGG9r0GrHtydU',
    appId: '1:883581912483:ios:2bca5756134bcc0d374616',
    messagingSenderId: '883581912483',
    projectId: 'kombinb2',
    storageBucket: 'kombinb2.appspot.com',
    iosClientId: '883581912483-9st0vo4ekf8b2kug1i9ro0mfot13h2tc.apps.googleusercontent.com',
    iosBundleId: 'com.example.kB2',
  );
}
